### ISSUE TITLE
error found on line no 7

### ISSUE THREAD

**Issue by smrutirdas** [smrutirdas/SkyDemo#1]
@sumidha hi sumidha find the error on line no 7

**Comment by bipeensinha** [comment]
I am working on it will updatye

**Comment by sumidha** [comment]
okay let me check

**Comment by smrutirdas** [comment]
thanks for the update

**Comment by bipeensinha** [comment]
![a](https://user-images.githubusercontent.com/49720823/140677709-c7391659-2b16-4b08-80f0-8b2677067617.png)
yahooooooooooooooooo i found the bug and fix it

**Comment by smrutirdas** [comment]
thanks closing the issue
